sqlplus/nolog
connect djohnson/Kirky2016!@ODSPEU1.ams
set echo off
set feedback off
set colsep ';'
set sqlprompt ''
set headsep off
set serveroutput on size unlimited
set linesize 30000
set trimspool on
set pagesize 0
set heading on
set trimout on
set wrap off
set termout off
spo u:\agoda.txt
SELECT 
pa.STATUSID
,PA.RECEIVEDDATE
,CO.DATEAUTHORISATION
,PA.SENDDATE
,PA.PAYMENTDATE
,PA.STATUSDATE
,co.MERCHANTID
,mm.MERCHANTNAME
,co.ORDERID
,co.CREDITCARDCOMPANY
,co.CREDITDEBITINDICATOR
,co.CVVINDICATOR
,co.CVVRESULT
,co.CVVSERVICEINDICATOR
,co.AVSINDICATOR
,co.AVSRESULT
,co.FRAUDCODE
,co.FRAUDINDICATOR
,co.FRAUDRESULT
,co.STTINDICATOR
,co.MERCHANTREFERENCE
,pa.PAYMENTREFERENCE
,co.CUSTOMERID
,co.COUNTRYCODE
,co.AUTHORISATIONCODE
,co.AUTHORISEDCURRENCYCODE
,co.AUTHORISEDAMOUNT
,co.AMOUNT
,o.SURNAME
,o.CITY
,o.PREFIXSURNAME
,o.STREET
,o.ZIP
,o.STATE
,sp.PROVIDERNAME
,co.PAYMENTPROCESSOR
,co.SERVICEPROVIDERID
,pa.PAYMENTMETHODID
,pa.PAYMENTPRODUCTID
,co.IIN
,CASE WHEN co.CVVINDICATOR = 1 then 'CVV Checked' WHEN co.CVVINDICATOR <> 1 then 'CVV Not Checked' END
,CASE WHEN co.CVVRESULT = 'M' THEN 'CVV Match' WHEN co.CVVRESULT = 'N' THEN 'CVV NoMatch' WHEN co.CVVRESULT not in ('N','M') THEN 'CVV Unknown' END
,CASE WHEN co.AVSRESULT in ('Z','A','W','D') THEN 'Partial AVS' WHEN co.AVSRESULT in ('X','Y','M','F','P') THEN 'Full AVS' WHEN co.AVSRESULT in ('N') THEN 'Neither ZIP nor address match' WHEN co.AVSRESULT in ('I') THEN 'AVS Not Performed' WHEN co.AVSRESULT in ('U','G','R','0','S') THEN 'Unsupp/Inconc AVS' END
,od.ipaddressmerchant
FROM EPS.PCO_CREDITCARDONLINE co
LEFT JOIN 
EPS.OPR_ORDER o
ON co.ORDERID=o.ORDERID
AND co.AMOUNT=o.AMOUNT
AND co.MERCHANTID=o.MERCHANTID
AND  co.AUTHORISEDCURRENCYCODE=o.CURRENCYCODE
LEFT JOIN EPS.GPM_SERVICEPROVIDER sp
ON co.SERVICEPROVIDERID=sp.SERVICEPROVIDERID
LEFT JOIN EPS.OPR_PAYMENTATTEMPT pa
ON co.MERCHANTID=pa.MERCHANTID
AND CO.AMOUNT =PA.AMOUNT
AND CO.ORDERID =PA.ORDERID
AND co.AUTHORISEDCURRENCYCODE=pa.CURRENCYCODE
AND co.ATTEMPTID=pa.ATTEMPTID
AND co.EFFORTID=pa.EFFORTID
LEFT JOIN EPS.MRM_MERCHANT mm
ON CO.MERCHANTID=mm.MERCHANTID
LEFT JOIN eps.opr_order od
on pa.merchantid = od.merchantid
and pa.orderid=od.orderid
and pa.amount=od.amount
WHERE co.AUTHORISATIONDATETIME>=TO_DATE('2017-12-01','YYYY-MM-DD')
AND CO.MERCHANTID =6485
AND PA.STATUSID=1050;
spo end