SELECT
	t1.STATUSID
	,t1.AUTHORISATIONDATETIME,t1.DATEAUTHORISATION,t1.STATUSDATE,t1.RECEIVEDDATE,t1.PAYMENTDATE
	,t1.MERCHANTID,t1.ORDERID,t1.CREDITCARDCOMPANY
	,t1.CREDITDEBITINDICATOR,t1.CVVINDICATOR,t1.CVVRESULT,t1.CVVSERVICEINDICATOR,t1.AVSINDICATOR,t1.AVSRESULT,t1.FRAUDCODE,t1.FRAUDINDICATOR,t1.FRAUDRESULT
	,t1.TVSRESULT, t1.EVSRESULT, t1.ZVSRESULT, t1.SVSRESULT, t1.NVSRESULT,t1.STTINDICATOR
	,t1.MERCHANTREFERENCE,t1.MERCHANTNAME,t1.PAYMENTREFERENCE --ADDED IN THE MERCHANT COUNTRY FROM ACCOUNT VALIDATION TABLE
	,t1.SUB_VERTICAL
	,t1.CUSTOMERID,t1.ISSUER_COUNTRY_CODE,t1.MERCHANT_COUNTRY_CODE
	,t1.AUTHORISEDCURRENCYCODE,t1.AUTHORISEDAMOUNT,t1.AMOUNT1,t1.AMOUNT2 --FLOW AND CURRENCY
	,t1.SURNAME, t1.CITY, t1.FIRSTNAME, t1.PREFIXSURNAME, t1.STREET,t1.ZIP,t1.STATE,t1.IPADDRESSMERCHANT,t1.IPADDRESSCUSTOMER
	,t1.PROVIDERNAME, t1.PROVIDERDESCRIPTION,t1.PAYMENTPROCESSOR,t1.SERVICEPROVIDERID,t1.PAYMENTMETHODID,t1.PAYMENTPRODUCTID,t2.DESCRIPTION,t3.PAYMENTPRODUCTNAME
	,t4.INTERCHANGE_RATE,t4.AVS_RESPONSE_MESSAGE,t1.IIN,t4.VANTIV_FLOW
	,t5.TRANSACTION_DATE, t5.SETTLEMENT_DATE, t5.INTERCHANGE_FLAT_RATE, t5.INTERCHANGE_PERCENT_RATE,t5.ISSUING_BANK,
	
CASE WHEN t1.CVVINDICATOR = 1 then 'CVV Checked'
WHEN t1.CVVINDICATOR <> 1 then 'CVV Not Checked'
END AS "CVVINDICATOR",

CASE WHEN t1.CVVRESULT = 'M' THEN 'CVV Match'
WHEN t1.CVVRESULT = 'N' THEN 'CVV NoMatch'
WHEN t1.CVVRESULT not in ('N','M') THEN 'CVV Unknown'
END AS "CVVRESULT",

CASE WHEN t1.AVSRESULT in ('Z','A','W','D') THEN 'Partial AVS'
WHEN t1.AVSRESULT in ('X','Y','M','F','P') THEN 'Full AVS'
WHEN t1.AVSRESULT in ('N') THEN 'Neither ZIP nor address match'
WHEN t1.AVSRESULT in ('I') THEN 'Information not verified for international transaction'
WHEN t1.AVSRESULT in ('U','G','R','0','S') THEN 'Unsupp/Inconc AVS'
END AS "AVSRESULT"

FROM
	(
		SELECT 
		pa.STATUSID
		,co.AUTHORISATIONDATETIME,co.DATEAUTHORISATION,pa.STATUSDATE,pa.RECEIVEDDATE,pa.PAYMENTDATE
		,co.MERCHANTID,co.ORDERID,co.CREDITCARDCOMPANY
		,co.CREDITDEBITINDICATOR,co.CVVINDICATOR,co.CVVRESULT,co.CVVSERVICEINDICATOR,co.AVSINDICATOR,co.AVSRESULT,co.FRAUDCODE,co.FRAUDINDICATOR,co.FRAUDRESULT
		,co.TVSRESULT, co.EVSRESULT, co.ZVSRESULT, co.SVSRESULT, co.NVSRESULT,co.STTINDICATOR
		,co.MERCHANTREFERENCE,m.MERCHANTNAME,m.COUNTRYCODE AS MERCHANT_COUNTRY_CODE, pa.PAYMENTREFERENCE --ADDED IN THE MERCHANT COUNTRY FROM ACCOUNT VALIDATION TABLE
		,mm. SUB_VERTICAL
		,co.CUSTOMERID,co.COUNTRYCODE AS ISSUER_COUNTRY_CODE
		,co.AUTHORISEDCURRENCYCODE,co.AUTHORISEDAMOUNT,co.AMOUNT AS AMOUNT1,pa.AMOUNT AS AMOUNT2 --FLOW AND CURRENCY
		,o.SURNAME, o.CITY, o.FIRSTNAME, o.PREFIXSURNAME, o.STREET,o.ZIP,o.STATE,o.IPADDRESSMERCHANT,o.IPADDRESSCUSTOMER
		,sp.PROVIDERNAME, sp.PROVIDERDESCRIPTION,co.PAYMENTPROCESSOR,co.SERVICEPROVIDERID,pa.PAYMENTMETHODID,pa.PAYMENTPRODUCTID,co.IIN
		FROM EPS.PCO_CREDITCARDONLINE co
		
		LEFT JOIN 
		EPS.OPR_ORDER o
		ON co.ORDERID=o.ORDERID
		AND co.AMOUNT=o.AMOUNT
		AND co.MERCHANTID=o.MERCHANTID
		AND  co.AUTHORISEDCURRENCYCODE=o.CURRENCYCODE
		
		LEFT JOIN EPS.GPM_SERVICEPROVIDER sp
		ON co.SERVICEPROVIDERID=sp.SERVICEPROVIDERID

		LEFT JOIN EPS.MRM_MERCHANT m
		ON co.MERCHANTID=m.MERCHANTID
		
		LEFT JOIN DATA.MB_MERCHANTS mm
		ON co.MERCHANTID=CONTRACT_ID

		LEFT JOIN EPS.OPR_PAYMENTATTEMPT pa
		ON co.MERCHANTID=pa.MERCHANTID
		AND co.AMOUNT=pa.AMOUNT
		AND co.ORDERID=pa.ORDERID
		AND co.AUTHORISEDCURRENCYCODE=pa.CURRENCYCODE
		AND co.ATTEMPTID=pa.ATTEMPTID
		AND co.EFFORTID=pa.EFFORTID

		WHERE co.AUTHORISATIONDATETIME>='2018-01-01'
		AND sp.PROVIDERDESCRIPTION LIKE '%Litle%'
        AND co.MERCHANTID=4856
		)t1
		LEFT JOIN
		(
		SELECT  
		pm.PAYMENTMETHODID, pm.PAYMENTTYPE, pm.PAYMENTMETHODNAME, pm.DESCRIPTION
		FROM EPS.GPM_PAYMENTMETHOD pm
		)t2
		ON t1.PAYMENTMETHODID=t2.PAYMENTMETHODID
		
		LEFT JOIN
		(
		SELECT  
		pp.PAYMENTPRODUCTID, pp.PAYMENTMETHODID, PAYMENTPRODUCTNAME
		FROM EPS.GPM_PAYMENTPRODUCT pp
		)t3
		ON t1.PAYMENTPRODUCTID=t3.PAYMENTPRODUCTID AND t1.PAYMENTMETHODID=t3.PAYMENTMETHODID
		LEFT JOIN
		(
		SELECT  
		v.ORDER_ID,v.INTERCHANGE_RATE,v.AVS_RESPONSE_MESSAGE,v.CONS_CORP_BIN,v.TRANSACTION_CURRENCY,v.TRANSACTION_FLOW*100 AS VANTIV_FLOW,v.CONTRACT_ID
		FROM DATA.ACQUIRER_VANTIV_COST v
		--WHERE v.INTERCHANGE_RATE LIKE '%EIRF%'
		)t4
		ON t1.ORDERID=t4.ORDER_ID 
		AND t1.MERCHANTID=t4.CONTRACT_ID
		AND t1.AMOUNT2=t4.VANTIV_FLOW
		LEFT JOIN
		(
		SELECT  
		v.ORDER_ID,v.INTERCHANGE_RATE AS IC_DESC,v.AVS_RESPONSE_MESSAGE,v.CONS_CORP_BIN,v.TRANSACTION_CURRENCY,v.TRANSACTION_FLOW*100 AS VANTIV_FLOW,v.CONTRACT_ID
		,v.TRANSACTION_DATE, v.SETTLEMENT_DATE, v.INTERCHANGE_FLAT_RATE, v.INTERCHANGE_PERCENT_RATE,v.ISSUING_BANK
		FROM DATA.ACQUIRER_VANTIV_COST v
		)t5
		ON t1.ORDERID=t5.ORDER_ID 
		AND t1.MERCHANTID=t5.CONTRACT_ID
		AND t1.AMOUNT2=t5.VANTIV_FLOW
WHERE t1.STATUSID=1050 	
AND CREDITCARDCOMPANY ='VISA'
GROUP BY
	t1.STATUSID
	,t1.AUTHORISATIONDATETIME,t1.DATEAUTHORISATION,t1.STATUSDATE,t1.RECEIVEDDATE,t1.PAYMENTDATE
	,t1.MERCHANTID,t1.ORDERID,t1.CREDITCARDCOMPANY
	,t1.CREDITDEBITINDICATOR,t1.CVVINDICATOR,t1.CVVRESULT,t1.CVVSERVICEINDICATOR,t1.AVSINDICATOR,t1.AVSRESULT,t1.FRAUDCODE,t1.FRAUDINDICATOR,t1.FRAUDRESULT
	,t1.TVSRESULT, t1.EVSRESULT, t1.ZVSRESULT, t1.SVSRESULT, t1.NVSRESULT,t1.STTINDICATOR
	,t1.MERCHANTREFERENCE,t1.MERCHANTNAME,t1.PAYMENTREFERENCE --ADDED IN THE MERCHANT COUNTRY FROM ACCOUNT VALIDATION TABLE
	,t1.SUB_VERTICAL
	,t1.CUSTOMERID,t1.ISSUER_COUNTRY_CODE,t1.MERCHANT_COUNTRY_CODE
	,t1.AUTHORISEDCURRENCYCODE,t1.AUTHORISEDAMOUNT,t1.AMOUNT1,t1.AMOUNT2 --FLOW AND CURRENCY
	,t1.SURNAME, t1.CITY, t1.FIRSTNAME, t1.PREFIXSURNAME, t1.STREET,t1.ZIP,t1.STATE,t1.IPADDRESSMERCHANT,t1.IPADDRESSCUSTOMER
	,t1.PROVIDERNAME, t1.PROVIDERDESCRIPTION,t1.PAYMENTPROCESSOR,t1.SERVICEPROVIDERID,t1.PAYMENTMETHODID,t1.PAYMENTPRODUCTID,t2.DESCRIPTION,t3.PAYMENTPRODUCTNAME
	,t4.INTERCHANGE_RATE,t4.AVS_RESPONSE_MESSAGE,t1.IIN, t4.VANTIV_FLOW,t5.IC_DESC,t5.CONS_CORP_BIN
	,t5.TRANSACTION_DATE, t5.SETTLEMENT_DATE, t5.INTERCHANGE_FLAT_RATE, t5.INTERCHANGE_PERCENT_RATE,t5.ISSUING_BANK
--AND t4.INTERCHANGE_RATE IS NOT NULL