SELECT
mm.MERCHANTNAME,CO.MERCHANTID,CO.CREDITCARDCOMPANY,CO.IIN,CC.PRODUCT_CODE,CO.RECURRING
,CO.ORDERID,py.PAYMENTREFERENCE,py.STATUSID,py.ATTEMPTID,CC.VOLUME,CO.PAYMENTPROCESSOR,PP.CC_ACQUIRER_NAME,PP.INTERCHANGE_REGION
,CC.TRANSACTION_TYPE,CO.CURRENCY,CO.AMOUNT AS FLOW,CC.NET_FLOW_EUR,CO.AVSINDICATOR,CO.AVSRESULT
,CO.NAME,CO.STREET,CO.CITY,CO.STATE,CO.COUNTRYCODE,CO.ZIP,
        CASE WHEN co.CVVINDICATOR = 1 then 'CVV Checked'
        WHEN co.CVVINDICATOR <> 1 then 'CVV Not Checked'
        END AS "CVVINDICATOR",
        CASE WHEN co.CVVRESULT = 'M' THEN 'CVV Match'
        WHEN co.CVVRESULT = 'N' THEN 'CVV NoMatch'
        WHEN co.CVVRESULT not in ('N','M') THEN 'CVV Unknown'
        END AS "CVVRESULT",
        CASE WHEN co.AVSRESULT in ('Z','A','W','D') THEN 'Partial AVS'
        WHEN co.AVSRESULT in ('X','Y','M','F','P') THEN 'Full AVS'
        WHEN co.AVSRESULT in ('N') THEN 'Neither ZIP nor address match'
        WHEN co.AVSRESULT in ('I') THEN 'Not verified for Intl trxn'
        WHEN co.AVSRESULT in ('U','G','R','0','S') THEN 'Unsupp/Inconc AVS'
        END AS "AVSRESULT_DESC"
FROM EPS.PCO_CREDITCARDONLINE co
LEFT JOIN FDWO.MB_PAYMENTPROCESSOR pp
ON CO.PAYMENTPROCESSOR=PP.PAYMENTPROCESSOR_ID
LEFT JOIN EPS.MRM_MERCHANT mm
ON CO.MERCHANTID=mm.MERCHANTID
LEFT JOIN EPS.OPR_PAYMENTATTEMPT py
ON CO.ORDERID=py.ORDERID
AND CO.MERCHANTID=py.MERCHANTID
AND CO.ATTEMPTID=py.ATTEMPTID
AND CO.AMOUNT=py.REQUESTAMOUNT
AND CO.CURRENCY=py.CURRENCYCODE
LEFT JOIN FDWO.CC_PROCESSING_DATA_PT cc
ON py.PAYMENTREFERENCE=CC.PAYMENTREFERENCE
AND py.ORDERID=CC.ORDERID
AND py.ATTEMPTID=CC.ATTEMPTID
AND py.MERCHANTID=CC.CONTRACT_ID
AND CO.PAYMENTPROCESSOR=CC.PAYMENT_PROCESSOR_NR
WHERE CO.AUTHORISATIONDATETIME BETWEEN TO_DATE('02/01/2018','MM/DD/YYYY') AND TO_DATE('02/02/2018','MM/DD/YYYY')
AND INTERCHANGE_REGION IN('EMEA','Europe')
AND py.STATUSID=1050
GROUP BY 
mm.MERCHANTNAME,CO.MERCHANTID,CO.CREDITCARDCOMPANY,CO.IIN,CC.PRODUCT_CODE,CO.RECURRING
,CO.ORDERID,py.PAYMENTREFERENCE,py.STATUSID,py.ATTEMPTID,CC.VOLUME,CO.PAYMENTPROCESSOR,PP.CC_ACQUIRER_NAME,PP.INTERCHANGE_REGION
,CC.TRANSACTION_TYPE,CO.CURRENCY,CO.AMOUNT,CC.NET_FLOW_EUR,CO.AVSINDICATOR,CO.AVSRESULT
,CO.NAME,CO.STREET,CO.CITY,CO.STATE,CO.COUNTRYCODE,CO.ZIP,co.CVVINDICATOR,co.AVSRESULT,co.CVVRESULT