SELECT 
bb.BAMBORA_REF
,TO_CHAR(bb.SETTLEMENT_DATE, 'MM') AS MONTH
,TO_CHAR(bb.SETTLEMENT_DATE, 'DD') AS DAY
,TO_CHAR(bb.SETTLEMENT_DATE, 'YYYY') AS YEAR
,TO_CHAR(bb.SETTLEMENT_DATE,'YYYY-MM') AS PERIOD
,bb.CONTRACT_ID,bb.ISSUER_COUNTRY_NAME, bb.MERCHANT_COUNTRY_NAME,bb.TRANSACTION_TYPE,bb.CARD_SCHEME,bb.CREDIT_DEBIT,bb.CONSUMER_CORPORATE,bb.REGIONALITY
,bb.SF_FIXED_FEE,bb.SF_PERC_FEE,bb.TRANSACTION_TYPE AS B_TRANSACTION_TYPE,bb.CONSUMER_CORPORATE AS C_TYPE
,bb.VOLUME AS VOLUME,ROUND(bb.TRANSACTION_AMOUNT_EUR) AS FLOW,bb.SCHEME_TOTAL_FEE_EUR AS SF,bb.TRANSACTION_AMOUNT_EUR
,BB.INTERCHANGE_TOTAL_FEE_EUR,BB.INTERCHANGE_TOTAL_FEE_EUR/bb.TRANSACTION_AMOUNT_EUR AS IC_BPS,BB.SCHEME_TOTAL_FEE_EUR/bb.TRANSACTION_AMOUNT_EUR AS SF_BPS
FROM fdwo.acquirer_bambora_cost bb
WHERE bb.TRANSACTION_TYPE='TRANSACTION'
AND bb.SETTLEMENT_DATE BETWEEN TO_DATE('01-01-2018','MM-DD-YYYY') AND TO_DATE('02-22-2018','MM-DD-YYYY')