
select *
from(
select t1.*,t2.Not_Authorized,t3.Authorized
from
(
select SERVICEACCOUNTNAME,CREDITCARDCOMPANY,IIN,VERTICAL,CURRENCY,CLIENT_NAME,COUNT(*) AS Total_Count
FROM
(
select CC.SERVICEPROVIDERID,CC.RESPONSEID,CC.PAYMENTPROCESSOR,SA.SERVICEACCOUNTNAME
,CC.CREDITCARDCOMPANY,CC.IIN,MM.VERTICAL,CC.CURRENCY,MM.CLIENT_NAME
from EPS.PCO_CREDITCARDONLINE cc
left join EPS.GPM_SERVICEACCOUNT sa
on CC.SERVICEPROVIDERID=SA.SERVICEPROVIDERID
and CC.PAYMENTPROCESSOR=SA.PAYMENTPROCESSORNUMBER
left join FDWO.MB_MERCHANTS mm
on CAST(CC.MERCHANTID as VARCHAR(25))=MM.CONTRACT_ID
where CC.SERVICEPROVIDERID is not null
and CC.DATEAUTHORISATION between to_date('11/1/2018','MM/DD/YYYY') and to_date('11/30/2018','MM/DD/YYYY')
)
GROUP BY SERVICEACCOUNTNAME,CREDITCARDCOMPANY, IIN, VERTICAL, CURRENCY, CLIENT_NAME
) t1
left join
(
select SERVICEACCOUNTNAME,CREDITCARDCOMPANY,IIN,VERTICAL,CURRENCY,CLIENT_NAME, COUNT(*) AS Authorized
from
(
select CC.SERVICEPROVIDERID,CC.RESPONSEID,CC.PAYMENTPROCESSOR,SA.SERVICEACCOUNTNAME,CC.CREDITCARDCOMPANY,CC.IIN,MM.VERTICAL,CC.CURRENCY,
MM.CLIENT_NAME
from EPS.PCO_CREDITCARDONLINE cc
left join EPS.GPM_SERVICEACCOUNT sa
on CC.SERVICEPROVIDERID=SA.SERVICEPROVIDERID
and CC.PAYMENTPROCESSOR=SA.PAYMENTPROCESSORNUMBER
left join FDWO.MB_MERCHANTS mm
on CAST(CC.MERCHANTID as VARCHAR(25))=MM.CONTRACT_ID
where CC.SERVICEPROVIDERID is not null
and CC.RESPONSEID=0
and CC.DATEAUTHORISATION between to_date('11/1/2018','MM/DD/YYYY') and to_date('11/30/2018','MM/DD/YYYY')
)
GROUP BY SERVICEACCOUNTNAME,CREDITCARDCOMPANY,IIN,VERTICAL,CURRENCY,CLIENT_NAME
)t2
on t1.SERVICEACCOUNTNAME=t2.SERVICEACCOUNTNAME
and t1.CREDITCARDCOMPANY=t2.CREDITCARDCOMPANY
and t1.VERTICAL=t2.VERTICAL
and t1.CURRENCY=t2.CURRENCY
and t1.CLIENT_NAME=t2.CLIENT_NAME
and t1.IIN=t2.IIN
left join
(
select SERVICEACCOUNTNAME,CREDITCARDCOMPANY,IIN,VERTICAL,CURRENCY,CLIENT_NAME,COUNT(*) AS Authorized
from
(
select CC.SERVICEPROVIDERID,CC.RESPONSEID,CC.PAYMENTPROCESSOR,SA.SERVICEACCOUNTNAME,CC.CREDITCARDCOMPANY,CC.IIN,MM.VERTICAL,CC.CURRENCY,MM.CLIENT_NAME
from EPS.PCO_CREDITCARDONLINE cc
left join EPS.GPM_SERVICEACCOUNT sa
on CC.SERVICEPROVIDERID=SA.SERVICEPROVIDERID
and CC.PAYMENTPROCESSOR=SA.PAYMENTPROCESSORNUMBER
left join FDWO.MB_MERCHANTS mm
on CAST(CC.MERCHANTID as VARCHAR(25))=MM.CONTRACT_ID
where CC.SERVICEPROVIDERID is not null
and CC.RESPONSEID <> 0
and CC.DATEAUTHORISATION between to_date('11/1/2018','MM/DD/YYYY') and to_date('11/30/2018','MM/DD/YYYY')
)
GROUP BY SERVICEACCOUNTNAME,CREDITCARDCOMPANY,IIN,VERTICAL,CURRENCY,CLIENT_NAME
)t3
on t1.SERVICEACCOUNTNAME=t3.SERVICEACCOUNTNAME
and t1.CREDITCARDCOMPANY=t3.CREDITCARDCOMPANY
and t1.VERTICAL=t3.VERTICAL
and t1.CURRENCY=t3.CURRENCY
and t1.CLIENT_NAME=t3.CLIENT_NAME
and t1.IIN=t3.IIN
) 

