sqlplus/nolog
connect djohnson/RhiBoo02!@ODSPEU1.ams
set echo off
set feedback off
set colsep ';'
set sqlprompt ''
set headsep off
set serveroutput on size unlimited
set linesize 30000
set trimspool on
set pagesize 0
set heading on
set trimout on
set wrap off
set termout off
spo \\amscifs01\homefolders$\djohnson\Desktop\global_avs.csv
SELECT 
co.MERCHANTID
,mm.MERCHANTNAME
,sp.PROVIDERNAME
,co.PAYMENTPROCESSOR
,co.CREDITCARDCOMPANY
,COUNT(co.ORDERID) AS VOLUME
,co.AVSRESULT
,co.AUTHORISEDCURRENCYCODE
,SUM(co.AMOUNT) AS FLOW
,CASE WHEN co.AVSRESULT in ('Z','A','W','D') THEN 'Partial AVS' WHEN co.AVSRESULT in ('X','Y','M','F','P') THEN 'Full AVS' WHEN co.AVSRESULT in ('N') THEN 'Neither ZIP nor address match' WHEN co.AVSRESULT in ('I') THEN 'AVS Not Performed' WHEN co.AVSRESULT in ('U','G','R','0','S') THEN 'Unsupp/Inconc AVS' END AS AVS_DESC
FROM EPS.PCO_CREDITCARDONLINE co
LEFT JOIN 
EPS.OPR_ORDER o
ON co.ORDERID=o.ORDERID
AND co.AMOUNT=o.AMOUNT
AND co.MERCHANTID=o.MERCHANTID
AND  co.AUTHORISEDCURRENCYCODE=o.CURRENCYCODE
LEFT JOIN EPS.GPM_SERVICEPROVIDER sp
ON co.SERVICEPROVIDERID=sp.SERVICEPROVIDERID
LEFT JOIN EPS.OPR_PAYMENTATTEMPT pa
ON co.MERCHANTID=pa.MERCHANTID
AND co.AMOUNT=pa.AMOUNT
AND co.ORDERID=pa.ORDERID
AND co.AUTHORISEDCURRENCYCODE=pa.CURRENCYCODE
AND co.ATTEMPTID=pa.ATTEMPTID
AND co.EFFORTID=pa.EFFORTID
LEFT JOIN FDWO.ACQUIRER_VANTIV_COST v
ON co.ORDERID=v.ORDER_ID
AND co.MERCHANTID=v.CONTRACT_ID
AND co.AMOUNT=v.TRANSACTION_FLOW*100
LEFT JOIN EPS.MRM_MERCHANT mm
ON CO.MERCHANTID=mm.MERCHANTID
WHERE co.AUTHORISATIONDATETIME BETWEEN TO_DATE('2017-04-01','YYYY-MM-DD') AND TO_DATE('2018-03-31','YYYY-MM-DD')
AND PA.STATUSID=1050
GROUP BY co.MERCHANTID,mm.MERCHANTNAME,sp.PROVIDERNAME,co.PAYMENTPROCESSOR,co.AVSRESULT,co.AUTHORISEDCURRENCYCODE,co.AVSRESULT,co.CREDITCARDCOMPANY;
spool off end