select Acquirer,PRODUCT_NAME,BN.TRANSACTION_TYPE,BN.CREDIT_DEBIT,BN.CONS_CORP,SUM(BN.TRANSACTION_FLOW_EUR) AS TRANSACTION_FLOW_EUR
from FDWO.ACQUIRER_BNP_COST bn
cross join
(select 'BNP' as Acquirer from dual)
left join
(select PRODUCT_NAME,PRODUCT_CODE from FDWO.MB_PRODUCT_CODE) pc
on bn.PRODUCT_CODE=PC.PRODUCT_CODE
where BN.CONTRACT_ID in('8423','8535')
and BN.TRANSACTION_DATE between to_date('7/1/2018','MM/DD/YYYY') and to_date('9/30/2018','MM/DD/YYYY')
group by BN.TRANSACTION_TYPE,BN.CREDIT_DEBIT,BN.CONS_CORP,Acquirer,PRODUCT_NAME
order by TRANSACTION_FLOW_EUR desc;
