SELECT CCO.CREDITCARDCOMPANY,CCO.PAYMENTPROCESSOR,SC.SERVICEACCOUNTNAME,pp.INTERCHANGE_REGION
FROM EPS.PCO_CREDITCARDONLINE cco

LEFT JOIN EPS.GPM_SERVICEACCOUNT sc
ON CCO.PAYMENTPROCESSOR=SC.PAYMENTPROCESSORNUMBER

LEFT JOIN FDWO.MB_PAYMENTPROCESSOR pp
ON CCO.PAYMENTPROCESSOR =pp.PAYMENTPROCESSOR_ID

WHERE CCO.AUTHORISATIONDATETIME BETWEEN TO_DATE('02/01/2017','MM/DD/YYYY') AND TO_DATE('01/31/2018','MM/DD/YYYY')
AND CCO.CREDITCARDCOMPANY='DISC'
AND INTERCHANGE_REGION IS NOT NULL
GROUP BY CCO.CREDITCARDCOMPANY,CCO.PAYMENTPROCESSOR,SC.SERVICEACCOUNTNAME,INTERCHANGE_REGION

