##Fee Excellence Query

select count(pa.orderid) AS COUNT,sum(pa.amount/100) AS FLOW,PA.CURRENCYCODE,pa.merchantid,pa.contractid,pa.statusid,PP.PAYMENTPRODUCTNAME,MM.CONTRACT_NAME,MM.CLIENT_NAME
,MM.CLIENT_ID,MM.INVOICE_RELATION_ID,MM.INVOICE_CURRENCY,MM.SALES_REGION,CC.SERVICEPROVIDERID,CC.PAYMENTPROCESSOR,pr.CC_ACQUIRER_NAME
from EPS.OPR_PAYMENTATTEMPT pa
left join EPS.GPM_PAYMENTPRODUCT pp
on PA.PAYMENTPRODUCTID=PP.PAYMENTPRODUCTID
and PA.PAYMENTMETHODID=PP.PAYMENTMETHODID
left join FDWO.MB_MERCHANTS mm
on CAST(PA.MERCHANTID AS VARCHAR(25))=MM.CONTRACT_ID
left join EPS.PCO_CREDITCARDONLINE cc
on PA.MERCHANTID=CC.MERCHANTID
and PA.EFFORTID=CC.EFFORTID
and PA.ATTEMPTID=CC.ATTEMPTID
and PA.ORDERID=CC.ORDERID
left join EPS.GPM_SERVICEACCOUNT sa
on CC.SERVICEPROVIDERID=SA.SERVICEPROVIDERID
and CC.PAYMENTPROCESSOR=SA.PAYMENTPROCESSORNUMBER
left join FDWO.MB_PAYMENTPROCESSOR pr
on CC.PAYMENTPROCESSOR=pr.paymentprocessor_id
where pa.amount/100<=1
and PA.STATUSID=99999
and PA.RECEIVEDDATE between to_date('1/1/2018','mm/dd/yyyy') and to_date('12/31/2018','mm/dd/yyyy')
and PA.PAYMENTPRODUCTID in(117,119,3,115,113,407)
group by pa.merchantid,pa.contractid,pa.statusid,PP.PAYMENTPRODUCTNAME,MM.CONTRACT_NAME,MM.CLIENT_NAME,MM.CLIENT_ID
,MM.INVOICE_RELATION_ID,MM.INVOICE_CURRENCY,MM.SALES_REGION,PA.CURRENCYCODE,CC.SERVICEPROVIDERID,CC.PAYMENTPROCESSOR,pr.CC_ACQUIRER_NAME;

##Volume Validation query

select count(pa.orderid) AS COUNT,sum(pa.amount/100) AS FLOW,PA.CURRENCYCODE,pa.merchantid,pa.contractid,pa.statusid,PP.PAYMENTPRODUCTNAME,MM.CONTRACT_NAME,MM.CLIENT_NAME
,MM.CLIENT_ID,MM.INVOICE_RELATION_ID,MM.INVOICE_CURRENCY,MM.SALES_REGION,CC.SERVICEPROVIDERID,CC.PAYMENTPROCESSOR,pr.CC_ACQUIRER_NAME
from EPS.OPR_PAYMENTATTEMPT pa
left join EPS.GPM_PAYMENTPRODUCT pp
on PA.PAYMENTPRODUCTID=PP.PAYMENTPRODUCTID
and PA.PAYMENTMETHODID=PP.PAYMENTMETHODID
left join FDWO.MB_MERCHANTS mm
on CAST(PA.MERCHANTID AS VARCHAR(25))=MM.CONTRACT_ID
left join EPS.PCO_CREDITCARDONLINE cc
on PA.MERCHANTID=CC.MERCHANTID
and PA.EFFORTID=CC.EFFORTID
and PA.ATTEMPTID=CC.ATTEMPTID
and PA.ORDERID=CC.ORDERID
left join EPS.GPM_SERVICEACCOUNT sa
on CC.SERVICEPROVIDERID=SA.SERVICEPROVIDERID
and CC.PAYMENTPROCESSOR=SA.PAYMENTPROCESSORNUMBER
left join FDWO.MB_PAYMENTPROCESSOR pr
on CC.PAYMENTPROCESSOR=pr.paymentprocessor_id
where PA.STATUSID>=900
and PA.STATUSID not in (99999)
and PA.STATUSID not in (1800)
and PA.STATUSID not in (1500)
and PA.RECEIVEDDATE between to_date('1/1/2018','mm/dd/yyyy') and to_date('12/31/2018','mm/dd/yyyy')
group by pa.merchantid,pa.contractid,pa.statusid,PP.PAYMENTPRODUCTNAME,MM.CONTRACT_NAME,MM.CLIENT_NAME,MM.CLIENT_ID
,MM.INVOICE_RELATION_ID,MM.INVOICE_CURRENCY,MM.SALES_REGION,PA.CURRENCYCODE,CC.SERVICEPROVIDERID,CC.PAYMENTPROCESSOR,pr.CC_ACQUIRER_NAME