select 
t4.MONTH,t4.contract_id,MM.CLIENT_NAME,t4.RELATION_ID,t4.product_code,t4.PRODUCT_NAME,t4.CARD_SCHEME,t4.INV_CURRENCY,t4.ACQUIRING_BANK,t5.icplus_type
,t4.PREVIOUS_MONTH_FIXED,t4.PREVIOUS_MONTH_PERC,t4.PREVIOUS_MONTH_FIXED_2,t4.PREVIOUS_MONTH_PERC_2,t4.FIXED_DIFF,t4.PERC_DIFF
from
(
(
select t1.contract_id,t1.RELATION_ID,t1.PRODUCT_NAME,t1.product_code,t1.CARD_SCHEME,t1.INV_CURRENCY,t1.ACQUIRING_BANK
,t1.MONTH
,t1.INV_TARIFF_FIXED AS PREVIOUS_MONTH_FIXED
,t1.INV_TARIFF_PERC AS PREVIOUS_MONTH_PERC
,t2.INV_TARIFF_FIXED AS PREVIOUS_MONTH_FIXED_2
,t2.INV_TARIFF_PERC AS PREVIOUS_MONTH_PERC_2
,CASE WHEN t1.INV_TARIFF_FIXED<>t2.INV_TARIFF_FIXED THEN 'Diff' END AS FIXED_DIFF
,CASE WHEN t1.INV_TARIFF_PERC<>t2.INV_TARIFF_PERC THEN 'Diff' END AS PERC_DIFF
from
(
select GM.CONTRACT_ID,GM.PRODUCT_CODE,GM.RELATION_ID,GM.ACQUIRING_BANK,PC.CARD_SCHEME,GM.MONTH
,GM.INV_TARIFF_FIXED,GM.INV_TARIFF_PERC,PREVIOUS_MONTH,CURRENT_YEAR,PC.PRODUCT_NAME,GM.INV_CURRENCY
from FDWO.GM_CALCULATION gm
cross join
(
select EXTRACT(MONTH FROM (CURRENT_DATE)) AS CURRENT_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-2 AS PREVIOUS_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-3 AS PREVIOUS_MONTH_2 
,EXTRACT(YEAR FROM (CURRENT_DATE)) AS CURRENT_YEAR
from dual
)
left join FDWO.MB_PRODUCT_CODE pc
on GM.PRODUCT_CODE=PC.PRODUCT_CODE
where EXTRACT(MONTH FROM (gm.MONTH))in (EXTRACT(MONTH FROM (CURRENT_DATE))-2)
and  EXTRACT(YEAR FROM (gm.MONTH))in (EXTRACT(YEAR FROM (CURRENT_DATE)))
GROUP BY GM.CONTRACT_ID,GM.PRODUCT_CODE,GM.RELATION_ID,GM.MONTH,GM.INV_TARIFF_FIXED
,GM.INV_TARIFF_PERC,PREVIOUS_MONTH,CURRENT_YEAR,CARD_SCHEME,PC.PRODUCT_NAME,GM.ACQUIRING_BANK,GM.INV_CURRENCY
)t1
left join
(
select GM.CONTRACT_ID,GM.PRODUCT_CODE,GM.RELATION_ID,GM.MONTH,GM.INV_TARIFF_FIXED
,GM.INV_TARIFF_PERC,PREVIOUS_MONTH_2,CURRENT_YEAR
from FDWO.GM_CALCULATION gm
cross join
(
select EXTRACT(MONTH FROM (CURRENT_DATE)) AS CURRENT_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-2 AS PREVIOUS_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-3 AS PREVIOUS_MONTH_2 
,EXTRACT(YEAR FROM (CURRENT_DATE)) AS CURRENT_YEAR
from dual
)
where EXTRACT(MONTH FROM (gm.MONTH))in (EXTRACT(MONTH FROM (CURRENT_DATE))-3)
and  EXTRACT(YEAR FROM (gm.MONTH))in (EXTRACT(YEAR FROM (CURRENT_DATE)))
GROUP BY GM.CONTRACT_ID,GM.PRODUCT_CODE,GM.RELATION_ID,GM.MONTH,GM.INV_TARIFF_FIXED
,GM.INV_TARIFF_PERC,PREVIOUS_MONTH_2,CURRENT_YEAR
)t2
on t1.contract_id=t2.contract_id
and t1.relation_id=t2.relation_id
and t1.product_code=t2.product_code
)t4
left join
(
select EXTRACT(MONTH FROM (match_date))AS MONTH,contract_id,product_code,invoice_currency,icplus_type,payment_processor 
from fdwo.cc_processing_data_pt
cross join
(
select EXTRACT(MONTH FROM (CURRENT_DATE)) AS CURRENT_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-2 AS PREVIOUS_MONTH
,EXTRACT(MONTH FROM (CURRENT_DATE))-3 AS PREVIOUS_MONTH_2 
,EXTRACT(YEAR FROM (CURRENT_DATE)) AS CURRENT_YEAR
from dual
)
where EXTRACT(MONTH FROM (match_date))=(EXTRACT(MONTH FROM (CURRENT_DATE)))-2
and  EXTRACT(YEAR FROM (match_date))in(EXTRACT(YEAR FROM (CURRENT_DATE)))
group by EXTRACT(MONTH FROM (match_date)),contract_id,product_code,invoice_currency,icplus_type,payment_processor
)t5
on t4.CONTRACT_ID=CAST(t5.CONTRACT_ID AS VARCHAR(25))
and t4.PRODUCT_CODE=t5.PRODUCT_CODE
and t4.INV_CURRENCY=t5.invoice_currency
and t4.ACQUIRING_BANK=t5.payment_processor
left join FDWO.MB_MERCHANTS mm
on t4.CONTRACT_ID=MM.CONTRACT_ID
)
--Where rownum<2000
where (t4.PERC_DIFF ='Diff' or t4.FIXED_DIFF ='Diff')
